gazebo:
  l_hip_yaw:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_hip_yaw:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0

  l_hip_roll:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_hip_roll:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0

  l_hip_pitch:
    position:
      p: 50.0
      d: 0.01
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_hip_pitch:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0

  l_knee:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_knee:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0

  l_ank_pitch:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 2.5
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_ank_pitch:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 2.5
      d: 0.0
      i: 0.1
      i_clamp: 10.0

  l_ank_roll:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
  r_ank_roll:
    position:
      p: 50.0
      d: 0.0
      i: 0.0
      i_clamp: 0.0
    velocity:
      p: 1.0
      d: 0.0
      i: 0.1
      i_clamp: 10.0
